a_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("a_posts.urls", namespace="a_posts")),  # Prefixed with 'posts/'
    path("", include("a_users.urls", namespace="a_users")),  # Prefixed with 'users/'
    path("a_inbox/", include("a_inbox.urls", namespace="a_inbox")),  # Prefixed with 'inbox/'
]

# Serving media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a_inbox/urls.py
from django.urls import path

from .views import *

app_name = "a_inbox"

urlpatterns = [ 
    path('', inbox_view, name='inbox'),
    path('conversation/<uuid:conversation_id>', inbox_view, name='inbox'),
    path('search_users/', search_users, name='search_users'),
    path('new_message/<recipient_id>', new_message, name='inbox_new_message'),
    path('new_reply/<conversation_id>', new_reply, name='inbox_newreply'),
    path('notify/<conversation_id>', notify_newmessage, name='notify_newmessage'),
    path('notify/inbox/', notify_inbox, name='notify_inbox'),
]

a_posts/urls.py
from django.urls import path

from .views import *

app_name = "a_posts"

urlpatterns = [
    ## Home page
    path("", home_view, name="home"),
    ## Create a new post
    path("post/create/", post_create_view, name="create_post"),
    ## All posts of a given tag (use a 'tag' prefix to differentiate)
    path("tag/<slug:tag>/", home_view, name="category"),
    ## Delete a post
    path("post/delete/<uuid:post_id>/", post_delete_view, name="delete_post"),
    ## Edit a post
    path("post/edit/<uuid:post_id>/", post_edit_view, name="edit_post"),
    ## Post page view
    path("post/<uuid:post_id>/", post_page_view, name="post"),
    ## Like a post
    path("post/like/<uuid:id>/", like_post, name="like_post"),
    ## Sent Comment
    path("comment/sent/<uuid:id>/", comment_sent, name="comment_sent"),
    ## Like a Comment
    path("comment/like/<uuid:id>/", like_comment, name="like_comment"),
    ## Delete Comment
    path("comment/delete/<uuid:id>/", comment_delete_view, name="comment_delete"),
    ## Sent Reply
    path("reply/sent/<uuid:id>/", reply_sent, name="reply_sent"),
    ## Like a Reply
    path("reply/like/<uuid:id>/", like_reply, name="like_reply"),
    ## Delete Reply
    path("reply/delete/<uuid:id>/", reply_delete_view, name="reply_delete"),
]

a_users/urls.py
from django.urls import path
from .views import *

app_name = "a_users"

urlpatterns = [
    ## Logged-in user's profile
    path("profile/", profile_view, name="profile"),
    ## Other users' profiles
    path("user/<str:username>/", profile_view, name="user_profile"),
    ## Edit profile
    path("profile/edit/", profile_edit_view, name="profile_edit"),
    ## Delete profile
    path("profile/delete/", profile_delete_view, name="profile_delete"),
    ## Onboarding Page
    path("profile_onboarding/", profile_onboarding, name="profile_onboarding"),
]

templates/includes/header.html
{% load static %}
<header x-data="{ mobilenavOpen: false }" class="md:flex items-center justify-between [&>*]:px-8 bg-gray-800 h-20 text-white sticky top-0 z-40">
    <div class="flex items-center justify-between h-20">
        <logo>
            <a class="flex items-center gap-1" href="{% url 'a_posts:home' %}">
                <img class="w-6 mr-1 -mt-1" src="{% static 'images/fireheart_white.svg' %}"/>
                <span class="text-lg font-bold">Awesome</span>
            </a>
        </logo>
        <mobileicon class="md:hidden">
            <a @click="mobilenavOpen = !mobilenavOpen" class="h-12 w-12 flex items-center justify-center cursor-pointer hover:bg-gray-700 rounded-lg">
                <img x-show="!mobilenavOpen" class="w-6 h-6 select-none" src="https://img.icons8.com/small/64/ffffff/menu.png"/> 
                <img x-show="mobilenavOpen" x-cloak class="w-6 h-6 select-none" src="https://img.icons8.com/small/64/ffffff/delete-sign.png"/>
            </a>
        </mobileicon>
    </div>
    <nav x-show="mobilenavOpen" x-cloak class="md:!block bg-gray-800 h-screen w-screen md:h-auto md:w-auto -mt-20 md:mt-0 absolute md:relative z-[-1]"
    x-transition:enter="duration-300 ease-out"
    x-transition:enter-start="opacity-0 -translate-y-96"
    x-transition:enter-end="opacity-100 translate-y-0">
        <ul class="flex items-center navitems flex-col md:flex-row gap-8 md:gap-0 justify-center h-full -translate-y-10 md:translate-y-0">
            {% if user.is_authenticated %}
            <li><a href="{% url 'a_posts:home' %}">Home</a></li>
            <li class="relative">
                <div class="absolute top-2 right-0"
                hx-get="{% url 'a_inbox:notify_inbox' %}"
                hx-trigger="load"
                hx-target="this"
                hx-swap="innerHTML">
                </div>
                <a href="{% url 'a_inbox:inbox' %}">Inbox</a>
            </li>
            <li><a href="{% url 'a_posts:create_post' %}">Create Post</a></li>
            <li x-data="{ dropdownOpen: false }" class="relative">
                <a @click="dropdownOpen = !dropdownOpen" @click.away="dropdownOpen = false" class="cursor-pointer select-none">
                    {% if user.is_authenticated %}
                    <img class="h-8 w-8 rounded-full object-cover" src="{{ user.profile.avatar }}"/>
                    {{ user.profile.name }}
                    {% endif %}
                    <img x-bind:class="dropdownOpen && 'rotate-180 duration-300'" class="w-4" src="https://img.icons8.com/small/32/777777/expand-arrow.png"/>
                </a>
                <div x-show="dropdownOpen" x-cloak class="absolute right-0 bg-white text-black shadow rounded-lg w-40 p-2 z-20"
                x-transition:enter="duration-300 ease-out"
                x-transition:enter-start="opacity-0 -translate-y-5 scale-90"
                x-transition:enter-end="opacity-100 translate-y-0 scale-100">
                    <ul class="hoverlist [&>li>a]:justify-end">
                        <li><a href="{% url 'a_users:profile' %}">My Profile</a></li>
                        <li><a href="{% url 'a_users:profile_edit' %}">Edit Profile</a></li>
                        <li><a href="{% url 'account_logout' %}">Log Out</a></li>
                    </ul>
                </div>
            </li>
            {% else %}
            <li><a href="{% url 'account_login' %}">Log In</a></li>
            <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
            {% endif %}
        </ul>
    </nav>
</header>

templates/includes/hero.html
<hero class="grid bg-gray-700 text-white text-center bg-cover z-10 relative bg-[url('https://live.staticflickr.com/65535/49909538937_3255dcf9e7_b.jpg')]">
    <div class="col-start-1 row-start-1 bg-gray-800 bg-opacity-40 w-full h-full"></div>
    <div class="col-start-1 row-start-1 py-24 px-10 ">
        <h1 class="font1 text-6xl title-fadein">Awesome Photos & Captions</h1>
        <p class="text-lg font-bold mb-5">Share your favorite Photos from Flickr and add a great caption</p>
        {% if not user.is_authenticated %}
        <a class="button" href="{% url 'account_signup' %}">Get Started</a>
        {% endif %}
    </div>
</hero>

templates/includes/messages.html
{% if messages %}
<div x-data="{ showMessage: false }" >
{% for message in messages %}
<div x-cloak class="absolute mx-auto left-0 right-0 mt-2 max-w-xl z-50 flex items-center 
            {% if message.tags == 'error' %}bg-red-500{% else %}bg-amber-300{% endif %} text-white p-3 rounded-lg" role="alert"
    x-show="showMessage" 
    x-init="setTimeout(() => showMessage = true, 200), setTimeout(() => showMessage = false, 6000)"
    x-transition:enter="duration-700 ease-out"
    x-transition:enter-start="opacity-0 -translate-y-5"
    x-transition:enter-end="opacity-100 translate-y-0"
    x-transition:leave="duration-200 ease-in"
    x-transition:leave-start="opacity-100 translate-y-0"
    x-transition:leave-end="opacity-0 -translate-y-5">
        <svg class="w-8 h-8 mr-2"  viewBox="0 0 512 512">
            <path d="M315.27,33,96,304H224L192.49,477.23a2.36,2.36,0,0,0,2.33,2.77h0a2.36,2.36,0,0,0,1.89-.95L416,208H288L319.66,34.75A2.45,2.45,0,0,0,317.22,32h0A2.42,2.42,0,0,0,315.27,33Z" style="fill:none;stroke:#ffffff;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px" fill="white"></path>
        </svg>
        <div>
            <div class="text-lg">{{ message }}</div>
        </div>
        <div class="ml-auto cursor-pointer" @click="showMessage = false">
            <svg fill="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24" stroke="currentColor" class="w-8 h-8 ml-2">
                <path d="M6 18L18 6M6 6l12 12"></path>
            </svg>
        </div>
    </div> 
{% endfor %}
</div>
{% endif %}

templates/includes/sidebar.html
{% load static %}
<aside x-show="mobileSidebarOpen" x-cloak class="md:!block col-span-full md:col-span-1 lg:mr-[20%] order-1 md:order-2"
    x-transition:enter="duration-300 ease-out"
    x-transition:enter-start="opacity-0 -mt-96"
    x-transition:enter-end="opacity-100 mt-0">
        <section class="card p-4">
            <h2>Categories</h2>
            <ul class="hoverlist">
                {% for category in categories %}
                <li class="{% if category.slug == tag.slug %} highlight {% endif %}">
                    <a href="{% url 'a_posts:category' category.slug %}">
                        <img class="w-8 h-8 object-cover mr-2" src="{{ category.image.url }}">
                        <span class="font-bold text-sm">{{ category.name }}</span>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </section>
        <section class="card p-4">
            <div class="flex items-center">
                <img class="w-7 mr-2 -mt-3" src="{% static 'images/fireheart_black.svg' %}"/>
                <h2>Top Posts</h2>
            </div>
            <ul class="hoverlist">
                {% for post in top_posts %}
                <li>
                    <a href="{% url 'a_posts:post' post.id %}" class="flex items-stretch justify-between">
                        <div class="flex items-center truncate">
                            <img class="w-10 h-10 rounded-lg object-cover mr-3 shrink-0" src="{{ post.image }}">
                            {% if post.author %}
                            <img class="w-6 h-6 rounded-full object-cover mr-1" src="{{ post.author.profile.avatar }}">
                            <span class="font-bold text-sm mr-1">{{ post.author.username }}</span>
                            {% else %}
                            <img class="w-6 h-6 rounded-full object-cover mr-1" src="{% static 'images/avatar_default.svg' %}">
                            <span class="font-bold text-sm mr-1">No Author</span>
                            {% endif %}
                        </div>
                        <span class="{% if user in post.likes.all %} font-bold {% else %} font-light {% endif %}text-sm text-grey-500 shrink-0">{{ post.likes.count }} Like{{ post.likes.count|pluralize:'s' }} / {{ post.comments.count }}</span>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </section>
        <section class="card p-4">
            <div class="flex items-center">
                <img class="w-7 mr-2 -mt-3" src="{% static 'images/fireheart_black.svg' %}"/>
                <h2>Top Comments</h2>
            </div>
            <ul class="hoverlist">
                {% for comment in top_comments %}
                <li>
                    <a href="{% url 'a_posts:post' comment.parent_post.id %}" class="flex items-stretch justify-between">
                        <div class="flex items-center truncate">
                            {% if comment.author %}
                            <img class="w-6 h-6 rounded-full object-cover mr-1" src="{{ comment.author.profile.avatar }}">
                            <span class="font-bold text-sm mr-1 truncate">{{ comment.author.profile.name }} : {{ comment.body|truncatechars:25 }}</span>
                            {% else %}
                            <img class="w-6 h-6 rounded-full object-cover mr-1" src="{% static 'images/avatar_default.svg' %}">
                            <span class="font-bold text-sm mr-1 truncate">No Author : {{ comment.body|truncatechars:25 }}</span>
                            {% endif %}
                        </div>
                        <span class="{% if user in comment.likes.all %} font-bold {% else %} font-light {% endif %}text-sm text-grey-500 shrink-0">{{ comment.likes.count }} Like{{ comment.likes.count|pluralize:'s' }} / {{ comment.replies.count }}</span>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </section>
    </aside>