a_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("a_posts.urls", namespace="a_posts")),  # Prefixed with 'posts/'
    path("", include("a_users.urls", namespace="a_users")),  # Prefixed with 'users/'
    path("a_inbox/", include("a_inbox.urls", namespace="a_inbox")),  # Prefixed with 'inbox/'
]

# Serving media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a_posts/urls.py
from django.urls import path

from .views import *

app_name = "a_posts"

urlpatterns = [
    ## Home page
    path("", home_view, name="home"),
    ## Create a new post
    path("post/create/", post_create_view, name="create_post"),
    ## All posts of a given tag (use a 'tag' prefix to differentiate)
    path("tag/<slug:tag>/", home_view, name="category"),
    ## Delete a post
    path("post/delete/<uuid:post_id>/", post_delete_view, name="delete_post"),
    ## Edit a post
    path("post/edit/<uuid:post_id>/", post_edit_view, name="edit_post"),
    ## Post page view
    path("post/<uuid:post_id>/", post_page_view, name="post"),
    ## Like a post
    path("post/like/<uuid:id>/", like_post, name="like_post"),
    ## Sent Comment
    path("comment/sent/<uuid:id>/", comment_sent, name="comment_sent"),
    ## Like a Comment
    path("comment/like/<uuid:id>/", like_comment, name="like_comment"),
    ## Delete Comment
    path("comment/delete/<uuid:id>/", comment_delete_view, name="comment_delete"),
    ## Sent Reply
    path("reply/sent/<uuid:id>/", reply_sent, name="reply_sent"),
    ## Like a Reply
    path("reply/like/<uuid:id>/", like_reply, name="like_reply"),
    ## Delete Reply
    path("reply/delete/<uuid:id>/", reply_delete_view, name="reply_delete"),
]

a_users/urls.py
from django.urls import path
from .views import *

app_name = "a_users"

urlpatterns = [
    ## Logged-in user's profile
    path("profile/", profile_view, name="profile"),
    ## Other users' profiles
    path("user/<str:username>/", profile_view, name="user_profile"),
    ## Edit profile
    path("profile/edit/", profile_edit_view, name="profile_edit"),
    ## Delete profile
    path("profile/delete/", profile_delete_view, name="profile_delete"),
    ## Onboarding Page
    path("profile_onboarding/", profile_onboarding, name="profile_onboarding"),
]

a_posts/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    image = models.FileField(upload_to='icons/', null=True, blank=True)
    slug = models.SlugField(max_length=100, unique=True)
    order = models.IntegerField(null=True)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ['order']

class Post(models.Model):
    title = models.CharField(max_length=500)
    artist = models.CharField(max_length=500, null=True)
    url = models.URLField(max_length=500, null=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='posts')
    image = models.URLField(max_length=500)
    body = models.TextField()
    likes = models.ManyToManyField(User, related_name='likedposts', through='LikedPost')
    tags = models.ManyToManyField(Tag, related_name='posts')
    created = models.DateTimeField(auto_now_add=True)
    id = models.CharField(max_length=100, default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        if len(self.title) > 50:
            return self.title[:50] + '...'
        return self.title
    
    class Meta:
        ordering = ['-created']


class LikedPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user.username} likes {self.post.title[:30]}'

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comments')
    parent_post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    likes = models.ManyToManyField(User, related_name='Likedcomments', through='LikedComment')
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self):
        try:
            return f'{self.author.username} : {self.body[:30]}'
        except:
            return f'no author : {self.body[:30]}'
    class Meta:
        ordering = ['-created_at']


class LikedComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} likes {self.comment.body[:30]}'


class Reply(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='replies')
    parent_comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    body = models.TextField()
    likes = models.ManyToManyField(
        User, related_name="Likedreplies", through="LikedReply"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )

    def __str__(self):
        try:
            return f'{self.author.username} : {self.body[:30]}'
        except:
            return f'no author : {self.body[:30]}'
    class Meta:
        ordering = ['created_at']

class LikedReply(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey(Reply, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.user.username} likes {self.reply.body[:30]}'

a_posts/forms.py
from django.forms import ModelForm
from django import forms
from .models import *


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["url", "body", "tags"]
        labels = {
            'body': 'Caption',
            'tags': 'Category',
        }
        widgets = {
            'url': forms.Textarea(attrs={'rows': 1, 'placeholder': 'Add a URL ...'}),
            'body': forms.Textarea(attrs={'rows': 3, 'placeholder': 'Add a Caption ... ', 'class': 'font1 text-4xl'}),
            'tags': forms.CheckboxSelectMultiple(),
        }


class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["body", "tags"]
        labels = {
            'body': 'Caption',
            'tags': 'Category'
        }
        widgets = {
            "body": forms.Textarea(
                attrs={"rows": 3, "class": "font1 text-4xl rounded-lg"}
            ),
            "tags": forms.CheckboxSelectMultiple(),
        }

class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        labels = {
            'body': ''
        }
        widgets = {
            "body": forms.TextInput(
                attrs={
                    "placeholder": "Add Comment...",
                    "class": "w-full",
                }
            ),
        }


class ReplyCreateForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['body']
        labels = {
            'body': ''
        }
        widgets = {
            "body": forms.TextInput(
                attrs={
                    "placeholder": "Add Reply...",
                    "class": "!text-sm w-full",
                }
            ),
        }

a_posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.db.models import Count
from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from bs4 import BeautifulSoup
import requests
from requests.exceptions import RequestException
from django.http import HttpResponse
from .models import *
from .forms import *


def home_view(request, tag=None):
    posts = Post.objects.filter(tags__slug=tag) if tag else Post.objects.all()

    if tag:
        tag = get_object_or_404(Tag, slug=tag)

    paginator = Paginator(posts, 3)
    page = int(request.GET.get('page', 1))
    try:
        posts = paginator.page(page)
    except:
        return HttpResponse('')
    
    context = {
        "posts": posts,
        "tag": tag,
        'page': page
    }
    
    
    if request.htmx:
        return render(request, 'snippets/loop_home_posts.html', context)

    return render(request, "a_posts/home.html", context)


def find_image(sourcecode):
    try:
        return sourcecode.select_one('meta[content^="https://live.staticflickr.com/"]')[
            "content"
        ]
    except (IndexError, TypeError):
        return None  # Handle missing image


def find_title(sourcecode):
    try:
        return sourcecode.select_one("h1.photo-title").text.strip()
    except (IndexError, TypeError):
        return "Untitled"  # Default title


def find_artist(sourcecode):
    try:
        return sourcecode.select_one("a.owner-name").text.strip()
    except (IndexError, TypeError):
        return "Unknown Artist"  # Default artist


@login_required
def post_create_view(request):
    if request.method == "GET":
        form = PostCreateForm()
    else:
        form = PostCreateForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)

            try:
                website = requests.get(form.cleaned_data["url"], timeout=10)
                website.raise_for_status()  # Ensure response is OK
                sourcecode = BeautifulSoup(website.content, "lxml")

                post.image = find_image(sourcecode)
                post.title = find_title(sourcecode)
                post.artist = find_artist(sourcecode)

            except (RequestException, AttributeError):
                messages.error(request, "Failed to retrieve data from the URL.")
                return render(request, "a_posts/post_create.html", {"form": form})

            post.author = request.user
            post.save()
            form.save_m2m()
            messages.success(request, "Post created successfully.")
            return redirect("a_posts:home")

    return render(request, "a_posts/post_create.html", {"form": form})


@login_required
def post_delete_view(request, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user)
    if request.method == "POST":
        post.delete()
        messages.success(request, "Post deleted successfully.")
        return redirect(reverse("a_posts:home"))

    return render(request, "a_posts/post_delete.html", {"post": post})


@login_required
def post_edit_view(request, post_id):
    post = get_object_or_404(Post, id=post_id, author=request.user)

    if request.method == "POST":
        form = PostEditForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, "Post updated successfully.")
            return redirect(reverse("a_posts:post", args=[post_id]))
    else:
        form = PostEditForm(instance=post)

    return render(request, "a_posts/post_edit.html", {"post": post, "form": form})


def post_page_view(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    
    reply_form = ReplyCreateForm()

    if request.htmx:
        if 'top' in request.GET:
            # comments = post.comments.filter(likes__isnull=False).distinct()
            comments = post.comments.annotate(num_likes=Count('likes')).filter(num_likes__gt=0).order_by('-num_likes')
        else:
            comments = post.comments.all()
        context = {
            'comments' : comments,
            'form' : reply_form, 
        }
        return render(request, 'snippets/loop_postpage_comments.html', context)

    comment_form = CommentCreateForm()

    context = {"form": comment_form, "post": post}

    return render(request, "a_posts/post_page.html", context)

@login_required
def comment_sent(request, id):
    post = get_object_or_404(Post, id=id)
    reply_form = ReplyCreateForm()
    if request.method == 'POST':
        comment_form = CommentCreateForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.parent_post = post
            new_comment.author = request.user
            new_comment.save()
            messages.success(request, "Comment added successfully.")
    context = {
        'comment' : new_comment,
        'post' : post,
        'form' : reply_form,
        }
    return render(request, 'snippets/add_comment.html', context)


@login_required
def comment_delete_view(request, id):
    comment = get_object_or_404(Comment, id=id, author=request.user)
    if request.method == "POST":
        comment.delete()
        messages.success(request, "Comment deleted successfully.")
        return redirect(reverse("a_posts:post", args=[comment.parent_post.id]))
    context = {
        'post' : comment.parent_post,
        'comment' : comment,
    }
    return render(request, "a_posts/comment_delete.html", context)

@login_required
def reply_sent(request, id):
    comment = get_object_or_404(Comment, id=id)
    reply_form = ReplyCreateForm()
    if request.method == 'POST':
        reply_form = ReplyCreateForm(request.POST)
        if reply_form.is_valid():
            new_reply = reply_form.save(commit=False)
            new_reply.parent_comment = comment
            new_reply.author = request.user
            new_reply.save()
            messages.success(request, "Reply added successfully.")
            reply_form = ReplyCreateForm()  # Reset the form after saving

    context = {
        'reply' : new_reply,
        'comment' : comment,
        'form': reply_form,
    }
    return render(request, 'snippets/add_reply.html', context)


@login_required
def reply_delete_view(request, id):
    reply = get_object_or_404(Reply, id=id, author=request.user)
    if request.method == "POST":
        reply.delete()
        messages.success(request, "Reply deleted successfully.")
        return redirect(reverse("a_posts:post", args=[reply.parent_comment.parent_post.id]))
    context = {
        "post": reply.parent_comment.parent_post,
        "reply": reply,
    }
    return render(request, "a_posts/reply_delete.html", context)


def like_toggle(model_cls):
    def innerfunc(func):
        def wrapper(request, *args, **kwargs):
            # Get the model instance using the id from kwargs
            model_instance = get_object_or_404(model_cls, id=kwargs.get("id"))
            user_exists = model_instance.likes.filter(
                username=request.user.username
            ).exists()

            # Ensure that the author can't like their own content
            if model_instance.author != request.user:
                if user_exists:
                    model_instance.likes.remove(request.user)
                    messages.success(request, "Unliked")
                else:
                    model_instance.likes.add(request.user)
                    messages.success(request, "Liked post.")

            # Call the decorated function without passing kwargs
            return func(request, model_instance, *args)  # Exclude kwargs

        return wrapper

    return innerfunc


@login_required
@like_toggle(Post)
def like_post(request, model_instance):
    context = {"post": model_instance}
    return render(request, "snippets/likes.html", context)


@login_required
@like_toggle(Comment)
def like_comment(request, model_instance):
    context = {"comment": model_instance}
    return render(request, "snippets/likes_comment.html", context)


@login_required
@like_toggle(Reply)
def like_reply(request, model_instance):
    context = {"reply": model_instance}
    return render(request, "snippets/likes_reply.html", context)

a_posts/templates/a_posts/comment.html
{% load static %}
<comment class="card p-4 !mb-4">
            <div class="flex justify-between items-center"> 
                {% if comment.author %}
                    <a class="flex items-center gap-1 mb-2" href="{% url 'a_users:user_profile' comment.author.username %}">
                        <img class="w-8 h-8 object-cover rounded-full" src="{{ comment.author.profile.avatar }}">
                        <span class="font-bold hover:underline">{{ comment.author.profile.name }}</span>
                        <span class="text-sm font-normal text-gray-400">@{{ comment.author.username }}</span>
                    </a>
                {% else %}
                    <div class="flex items-center gap-1 mb-4">
                        <img class="w-8 h-8 object-cover rounded-full" src="{% static 'images/avatar_default.svg' %}"
                        <span class="text-gray-500">No Author</span>
                    </div>
                {% endif %}
            </div>
            <p class="text-xl px-2">
                {{ comment.body }}
            </p>
            <div x-data="{ repliesOpen: false }" class="flex items-center justify-between flex-wrap text-sm px-2">
                {% if comment.replies.count or user.is_authenticated %}
                <a @click="repliesOpen = !repliesOpen" class="font-bold hover:underline cursor-pointer">
                    <div class="inline-block" x-bind:class="repliesOpen && 'rotate-90 duration-300'">
                        <svg transform ="rotate(90)" width="9" height="9" viewBox="0 0 25 25">
                            <path d="M24 22h-24l12-20z"/>
                        </svg>
                    </div>
                    {% if comment.replies.count %}
                    Replies
                    {% else %}
                    {% if user.is_authenticated %} Add Reply {% endif %}
                    {% endif %}
                    <span id="repliescount{{ comment.id }}" class="font-light text-gray-500 ml-1">{{ comment.replies.count }}</span>
                </a>
                {% endif %}
                <div  class="flex items-center gap-4 [&>a:hover]:underline">
                    {% include 'snippets/likes_comment.html' %}
                    {% if user.is_authenticated and comment.author == user %}
                    <a href="{% url 'a_posts:comment_delete' comment.id %}">Delete</a>
                    {% endif %}
                </div>

                <div x-show="repliesOpen" x-cloak class="basis-full mt-3 pl-8 grid grid-cols-1">
                    {% for reply in comment.replies.all %}
                    {% include 'a_posts/reply.html' %}
                    {% endfor %}    

                    {% if user.is_authenticated %}
                    <form class="flex items-center p-4 space-x-2" autocomplete="off" 
                    hx-post="{% url 'a_posts:reply_sent' comment.id %}"
                    hx-target="this"
                    hx-swap="outerHTML"
                    hx-on="htmx:afterRequest: reset()">
                        {% csrf_token %}
                        <div class="flex-grow">
                            {{ form }}
                        </div>
                        <button @click="open = false" class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors" type="submit">Submit</button>
                    </form>
                    {% endif %}
                </div>
            </div> 
        </comment>

a_posts/templates/a_posts/comment_delete.html
{% extends 'layouts/b.html' %}

{% block content %}

<h1>Delete Comment</h1>

{% include 'a_posts/comment.html' %}

<p class="my-6">Are you sure you want to delete this comment?</p>

<form action="{% url 'a_posts:comment_delete' comment.id %}" method='POST'>
    {% csrf_token %}
    <button type="submit">Confirm</button>
    <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
</form>

{% endblock content %}

a_posts/templates/a_posts/direct_message.html
<wrapper class="block h-[calc(100%-20px)] max-w-2xl mx-auto my-10">
    <h2>Direct Message</h2>
    
    <div id="chat_window" class="flex flex-col h-full bg-gray-800 rounded-2xl shadow-2xl relative p-1">
        <a href="{% url 'a_users:user_profile' user.username %}">
            <div class="flex items-center gap-2 p-4 sticky top-0 z-10">
                <div id="user_online_icon" class="gray-dot absolute top-2 left-2"></div>
                <img class="w-10 h-10 rounded-full object-cover" src="{{ user.profile.avatar }}" />
                <div>
                    <span class="font-bold text-white">{{ user.profile.name }}</span> 
                    <span class="text-sm font-light text-gray-400">@{{ user.username }}</span>
                </div>
            </div>
        </a>
        
        <div id="chat_container" class="overflow-y-auto grow">
            <ul id="chat_messages" class="flex flex-col justify-end gap-2 p-4">
                <!-- Chat messages will go here -->
            </ul>
        </div>
        
        <div class="sticky bottom-0 h-30 z-10 p-2 bg-gray-800">
            <form id="chat_message_form" method="POST" class="w-full nolabel h-14"
                hx-ext="ws" 
                ws-connect="/ws/group/6NaAPmAEvpgZsqdSDzrHr5" 
                ws-send
                _="on htmx:wsAfterSend reset() me">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                <div>
                    <label for="id_body">Body:</label>
                    <input type="text" name="body" placeholder="Add message ..." class="p-4 text-black" maxlength="300" autofocus id="id_body">
                </div>
            </form>
        </div>
    </div>
</wrapper>

<script>
    function scrollToBottom(time=0) {
        setTimeout(function() {
            const container = document.getElementById('chat_container');
            container.scrollTop = container.scrollHeight;
        }, time);
    }
    scrollToBottom();
    scrollToBottom(300);

    
</script>

a_posts/templates/a_posts/home.html
{% extends 'layouts/a.html' %}

{% block content %}


        {% for post in posts %}
            {% include 'a_posts/post.html' %}
        {% endfor %}


        <div 
        hx-get="{% if tag %}{% url 'a_posts:category' tag.slug %}{% else %}{% url 'a_posts:home' %}{% endif %}?page={{ page|add:1 }}"
        hx-trigger="revealed"
        hx-target="this"
        hx-swap="outerHTML">
        </div>

{% endblock content%}

a_posts/templates/a_posts/post.html
{% load static %}
<article class="card">
            <div class="flex items-center justify-between px-4 h-14">
                <h3 class="text-start leading-5 mr-1">{{ post.title }}</h3>
                <div class="text-sm text-gray-400 truncate">flickr<a href="{{ post.url }}" class="hover:underline ml-1" target="blank">@{{ post.artist }}</a></div>
            </div>
            <figure>
                <a href="{% url 'a_posts:post' post.id %}"><img class="w-full" src="{{ post.image }}"></a>
            </figure>
            <div class="p-4 pb-2">
                {% if post.author %}
                <a class="flex items-center gap-1 mb-4" href="{% url 'a_users:user_profile' post.author.username %}">
                    <img class="w-8 h-8 object-cover rounded-full" src="{{ post.author.profile.avatar }}">
                    <span class="font-bold hover:underline">{{ post.author.profile.name }}</span>
                    <span class="text-sm text-gray-400">@{{ post.author.username }}</span>
                </a>
                {% else %}
                <div class="flex items-center gap-1 mb-4">
                    <img class="w-8 h-8 object-cover rounded-full" src="{% static 'images/avatar_default.svg' %}">
                    <span class="font-bold hover:underline">Author Name</span>
                    <span class="text-sm text-gray-400">@username</span>
                </div>
                {% endif %}
                <p class="text-5xl mb-10 px-4 font1">{{ post.body }}</p>
                <div class="flex items-center gap-2 text-sm mb-5 flex-wrap">
                    {% for tag in post.tags.all %}
                        <a href="{% url 'a_posts:category' tag.slug %}" class="bg-gray-200 rounded-full px-3 py-1 hover:bg-gray-800 hover:text-white">{{ tag.name }}</a>
                    {% endfor %}
                </div>
                <div class="flex items-center justify-between text-sm px-2">
                    <a class="font-bold hover:underline" href="{% url 'a_posts:post' post.id %}">
                        {% if post.comments.count %}
                        Comments
                        <span id="commentscount{{ post.id }}" class="font-light text-gray-500 ml-1">{{ post.comments.count }}</span>
                        {% else %}
                            {% if user.is_authenticated %}
                            Add Comment 
                            {% endif %}
                        {% endif %}
                    </a>
                    <div class="flex items-center gap-4 [&>a:hover]:underline">
                        {% include 'snippets/likes.html' %}
                        {% if user.is_authenticated and user == post.author %}
                        <a href="{% url 'a_posts:edit_post' post.id %}">Edit</a>
                        <a href="{% url 'a_posts:delete_post' post.id %}">Delete</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </article>

a_posts/templates/a_posts/post_create.html
{% extends 'layouts/b.html' %}

{% block content %}

<h1>Create Post</h1>
<div class="card !p-8">
    
    <div class="flex items-center mb-6">
        <img class="h-5 object-cover mr-1" src="https://img.icons8.com/small/96/333333/search--v1.png"/>
        <a href="https://www.flickr.com/explore" target="_blank" class="hover:underline text-gray-500">Find an image on Flickr</a>
    </div>

    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="mt-1">Submit Post</button>
        <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
    </form>
</div>

{% endblock content %}

a_posts/templates/a_posts/post_delete.html
{% extends 'layouts/b.html' %}

{% block content %}

<div class="md:flex items-center">
    <div class="w-full md:max-w-sm mr-6 md:[&>*>*>p]:text-4xl">
        {% include 'a_posts/post.html' %}
    </div>
    <div>
        <h1>Delete Post</h1>
        <p class="mb-6">Are you sure you want to delete this post?</p>
        
        <form method='POST'>
            {% csrf_token %}
            <button type="submit">Confirm</button>
            <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
        </form>
    </div>
</div>

{% endblock content %}

a_posts/templates/a_posts/post_edit.html
{% extends 'layouts/b.html' %}

{% block content %}

<h1>Edit Post</h1>
<div class="card p-4">
    <div class="flex items-center mb-4">
        <img class="w-20 h-20 object-cover rounded-xl mr-4" src="{{ post.image }}">
        <h3 class="text-lg font-bold">{{ post.title }}</h3>
    </div>
    
    <div class="pb-2">
        <form method='POST'>
            {% csrf_token %}
            {{ form.as_p }}
            <div class="pt-4">
                <button type="submit">Submit</button>
                <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER}}">Go Back</a>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

a_posts/templates/a_posts/post_page.html
{% extends 'layouts/a.html' %}



{% block content %}

{% include 'a_posts/post.html' %}

<div class="card !pb-0 -mt-3">
    {% if user.is_authenticated %}
    <form class="flex items-center p-4 space-x-2" autocomplete="off"
    hx-post="{% url 'a_posts:comment_sent' post.id %}" 
    hx-target="#tab-contents"
    hx-swap="afterbegin"
    _="on htmx:afterRequest reset() me">
        {% csrf_token %}
        <div class="flex-grow">
            {{ form }}
        </div>
        <button @click="open = false" class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors" type="submit">Submit</button>
    </form>
    {% endif %}
</div>



<div class="mb-20">
    <div id="tabs" class="ml-4 flex gap-1 {% if not post.comments.count %} hidden {% endif %} mb-4"  hx-target="#tab-contents" hx-swap="innerHTML"
    _="on htmx:afterOnLoad take .selected for event.target">
        <a hx-get="{% url 'a_posts:post' post.id %}" class="tab selected">Newest First</a> 
        <a hx-get="{% url 'a_posts:post' post.id %}?top" class="tab">Top Comments</a>
    </div>

    <div id="tab-contents">
        {% for comment in post.comments.all %}
            {% include 'a_posts/comment.html' %}
        {% endfor %}
    </div>
</div>



{% endblock content %}

a_posts/templates/a_posts/reply.html
{% load static %}
                    <reply class="flex items-end justify-between py-4 border-t">
                        <div class="flex">
                            <a href="{% url 'a_users:user_profile' reply.author.username %}">
                                {% if reply.author %}
                                <img class="w-8 h-8 object-cover rounded-full mr-2" src="{{ reply.author.profile.avatar }}">
                                {% else %}
                                <img class="w-8 h-8 object-cover rounded-full mr-2" src="{% static 'images/avatar_default.svg' %}">
                                {% endif %}
                            </a>
                            <div class="w-fit">
                                {% if reply.author %}
                                <a class="block" href="">
                                    <span class="font-bold hover:underline">{{ reply.author.profile.name }}</span>
                                    <span class="text-sm text-gray-400">@{{ reply.author.username }}</span>
                                </a>
                                {% else %}
                                <span class="font-bold text-gray-400">No Author</span>
                                {% endif %}
                                <div class="mr-3">{{ reply.body }}</div>
                            </div>
                        </div>
                        <div class="flex items-center gap-4 [&>a:hover]:underline">
                            {% include 'snippets/likes_reply.html' %}
                            {% if user.is_authenticated and reply.author == user %}
                            <a href="{% url 'a_posts:reply_delete' reply.id %}">Delete</a>
                            {% endif %}
                        </div>
                    </reply>

a_posts/templates/a_posts/reply_delete.html
{% extends 'layouts/b.html' %}

{% block content %}

<h1>Delete Reply</h1>

<div class=" card px-6 pt-3 text-md mb-6 [&>*>*>a]:text-sm">

    {% include 'a_posts/reply.html' %}

</div>

<p class="mb-6">Are you sure you want to delete this reply?</p>

<form method='POST' action="{% url 'a_posts:reply_delete' reply.id %}">
    {% csrf_token %}
    <button type="submit">Confirm</button>
    <a class="button secondaryAction ml-1" href="{{ request.META.HTTP_REFERER }}">Go Back</a>
</form>


{% endblock content %}