a_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("a_posts.urls", namespace="a_posts")),  # Prefixed with 'posts/'
    path("", include("a_users.urls", namespace="a_users")),  # Prefixed with 'users/'
    path("a_inbox/", include("a_inbox.urls", namespace="a_inbox")),  # Prefixed with 'inbox/'
]

# Serving media files during development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

a_posts/urls.py
from django.urls import path

from .views import *

app_name = "a_posts"

urlpatterns = [
    ## Home page
    path("", home_view, name="home"),
    ## Create a new post
    path("post/create/", post_create_view, name="create_post"),
    ## All posts of a given tag (use a 'tag' prefix to differentiate)
    path("tag/<slug:tag>/", home_view, name="category"),
    ## Delete a post
    path("post/delete/<uuid:post_id>/", post_delete_view, name="delete_post"),
    ## Edit a post
    path("post/edit/<uuid:post_id>/", post_edit_view, name="edit_post"),
    ## Post page view
    path("post/<uuid:post_id>/", post_page_view, name="post"),
    ## Like a post
    path("post/like/<uuid:id>/", like_post, name="like_post"),
    ## Sent Comment
    path("comment/sent/<uuid:id>/", comment_sent, name="comment_sent"),
    ## Like a Comment
    path("comment/like/<uuid:id>/", like_comment, name="like_comment"),
    ## Delete Comment
    path("comment/delete/<uuid:id>/", comment_delete_view, name="comment_delete"),
    ## Sent Reply
    path("reply/sent/<uuid:id>/", reply_sent, name="reply_sent"),
    ## Like a Reply
    path("reply/like/<uuid:id>/", like_reply, name="like_reply"),
    ## Delete Reply
    path("reply/delete/<uuid:id>/", reply_delete_view, name="reply_delete"),
]

templates/snippets/add_comment.html
<fade-in 
class="opacity-0 block -mt-20 ease-in-out"
_="on load transition my margin-top to 0 over 0.2 seconds then transition my opacity to 1 over 0.4 seconds" >
    {% include 'a_posts/comment.html' %}
</fade-in>
<span
hx-swap-oob="true"
id="commentscount{{ post.id }}"
class="font-light text-gray-500 ml-1">{{ post.comments.count }}</span>

templates/snippets/add_reply.html
<fade-in 
class="opacity-0 block -mt-20 ease-in-out"
_="on load transition my margin-top to 0 over 0.2 seconds then transition my opacity to 1 over 0.4 seconds" >
    {% include 'a_posts/reply.html' %}
</fade-in>

<form class="flex items-center p-4 space-x-2" autocomplete="off" 
    hx-post="{% url 'a_posts:reply_sent' comment.id %}"
    hx-target="this"
    hx-swap="outerHTML"
    hx-on="htmx:afterRequest: reset()">
    {% csrf_token %}
    <div class="flex-grow">
        {{ form }}
    </div>
    <button @click="open = false" class="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors" type="submit">Submit</button>
</form>

<span hx-swap-oob="true" id="repliescount{{ comment.id }}" class="font-light text-gray-500 ml-1">
    {{ comment.replies.count }}
</span>

templates/snippets/likes.html
{% load static %}
<div class="flex items-center gap-4 [&>a:hover]:underline">
    {% if post.likes.count %}
        <div class="flex items-center gap-1">
            {% if user in post.likes.all %}
            <img class="w-5 -mt-1" src="{% static 'images/fireheart_red.svg' %}">
            {% else %}
            <img class="w-5 -mt-1" src="{% static 'images/fireheart.svg' %}">
            {% endif %}
            {{ post.likes.count }}
        </div>
    {% endif %}
    {% if user.is_authenticated and user != post.author %}
    <a class="cursor-pointer" 
        hx-get="{% url 'a_posts:like_post' post.id %}"
        hx-target="closest div"
        hx-swap="outerHTML" >
        {% if user in post.likes.all %}
            <b>Liked</b>
            {% else %}
            Like
            {% endif %}
        </a>
    {% endif %}
</div>

templates/snippets/likes_comment.html
{% load static %}
<div class="flex items-center gap-4 [&>a:hover]:underline">
    {% if comment.likes.count %}
        <div class="flex items-center gap-1">
            {% if user in comment.likes.all %}
            <img class="w-5 -mt-1" src="{% static 'images/fireheart_red.svg' %}">
            {% else %}
            <img class="w-5 -mt-1" src="{% static 'images/fireheart.svg' %}">
            {% endif %}
            {{ comment.likes.count }}
        </div>
    {% endif %}
    {% if user.is_authenticated and user != comment.author %}
    <a class="cursor-pointer" 
        hx-get="{% url 'a_posts:like_comment' comment.id %}"
        hx-target="closest div"
        hx-swap="outerHTML" >
        {% if user in comment.likes.all %}
            <b>Liked</b>
            {% else %}
            Like
            {% endif %}
        </a>
    {% endif %}
</div>

templates/snippets/likes_reply.html
{% load static %}
<div class="flex items-center gap-4 [&>a:hover]:underline">
    {% if reply.likes.count %}
        <div class="flex items-center gap-1">
            {% if user in reply.likes.all %}
            <img class="w-5 -mt-1" src="{% static 'images/fireheart_red.svg' %}">
            {% else %}
            <img class="w-5 -mt-1" src="{% static 'images/fireheart.svg' %}">
            {% endif %}
            {{ reply.likes.count }}
        </div>
    {% endif %}
    {% if user.is_authenticated and user != reply.author %}
    <a class="cursor-pointer" 
        hx-get="{% url 'a_posts:like_reply' reply.id %}"
        hx-target="closest div"
        hx-swap="outerHTML" >
        {% if user in reply.likes.all %}
            <b>Liked</b>
            {% else %}
            Like
            {% endif %}
        </a>
    {% endif %}
</div>

templates/snippets/loop_home_posts.html
<fade-in class="opacity-0" _="on load transition my opacity to 1 over 0.3 seconds">


    {% for post in posts %}
    {% include 'a_posts/post.html' %}
    {% endfor %}


    <div 
    hx-get="{% if tag %}{% url 'a_posts:category' tag.slug %}{% else %}{% url 'a_posts:home' %}{% endif %}?page={{ page|add:1 }}"
    hx-trigger="revealed"
    hx-target="this"
    hx-swap="outerHTML">
    </div>


</fade-in>

templates/snippets/loop_postpage_comments.html
<fade-in class="opacity-0" _="on load transition my opacity to 1 over 0.2 seconds">

    {% for comment in comments %}
        {% include 'a_posts/comment.html' %}
    {% endfor %}

</fade-in>

templates/snippets/loop_profile_comments.html
</fade-in><fade-in class="opacity-0" _="on load transition my opacity to 1 over 0.2 seconds">

    <div class="w-full lg:w-[50rem] mx-auto">

        {% if comments %}

            {% for comment in comments %}
                <div class="flex gap-2">
                    <a href="{% url 'a_posts:post' comment.parent_post.id %}">
                        <img class="w-20 h-20 object-cover rounded-xl hover:scale-95 max-w-none" src="{{ comment.parent_post.image }}">
                    </a>
                    {% include 'a_posts/comment.html' %}
                </div>
            {% endfor %}

        {% else %}

            <div class="w-full text-center mt-10"> No Comments Yet! </div>

        {% endif %}
    </div>

</fade-in>

templates/snippets/loop_profile_posts.html
<fade-in class="fade-in opacity-0" _="on load transition my opacity to 1 over 0.2 seconds">

    <div class="grid place-items-start gap-x-8 mx-auto max-w-xl grid-cols-1
        {% if posts|length == 2 %} lg:grid-cols-2 lg:max-w-5xl
        {% elif posts|length > 2 %} lg:grid-cols-2 lg:max-w-5xl xl:grid-cols-3 xl:max-w-7xl
        {% endif %}
    ">

        {% if posts %}
            {% for post in posts %}
                {% include 'a_posts/post.html' %}
            {% endfor %}
        {% else %}
            <div class="w-full text-center mt-10"> No Posts Yet! </div>
        {% endif %}

    </div>
</fade-in>